import json
import boto3
import os

# ----------------------------
# DynamoDB
# ----------------------------
dynamodb = boto3.resource("dynamodb")
table = dynamodb.Table(os.environ["IDEAS_TABLE"])

def get_idea(user_id: str, idea_id: str):
    response = table.get_item(
        Key={
            "userId": user_id,
            "ideaId": idea_id
        }
    )
    return response.get("Item")

# ----------------------------
# SES
# ----------------------------
ses = boto3.client("ses", region_name="us-east-1")
SENDER_EMAIL = os.environ["SENDER_EMAIL"]

# ----------------------------
# Lambda handler
# ----------------------------
def lambda_handler(event, context):
    try:
        body = json.loads(event["body"])

        user_id = body.get("userId")
        idea_id = body.get("ideaId")
        email = body.get("email")

        if not user_id or not idea_id or not email:
            return response(400, {"error": "Missing required fields"})

        item = get_idea(user_id, idea_id)

        if not item:
            return response(404, {"error": "Idea not found"})

        idea = item.get("idea_json", {})

        html_body = build_email_html(idea)

        ses.send_email(
            Source=SENDER_EMAIL,
            Destination={"ToAddresses": [email]},
            Message={
                "Subject": {
                    "Data": f"Your InstaIdea: {idea.get('title', 'Untitled')}"
                },
                "Body": {
                    "Html": {"Data": html_body}
                }
            }
        )

        return response(200, {"message": "Email sent successfully"})

    except Exception as e:
        print("❌ Error:", e)
        return response(500, {"error": str(e)})

# ----------------------------
# Helpers
# ----------------------------
def build_email_html(idea):

    def section(title, value):
        if isinstance(value, list):
            if value:
                items = "".join(f"<li>{v}</li>" for v in value)
                content = f"<ul>{items}</ul>"
            else:
                content = "<p>—</p>"
        else:
            content = f"<p>{value}</p>" if value else "<p>—</p>"

        return f"""
        <h3 style="margin-bottom:4px;">{title}</h3>
        {content}
        """

    return f"""
    <html>
      <body style="font-family: Arial, sans-serif; color: #111; line-height:1.5;">
        <h1>{idea.get('title', 'Untitled idea')}</h1>

        {section("Possible names", idea.get("possible_names"))}
        {section("Description", idea.get("description"))}
        {section("Problem", idea.get("problem"))}
        {section("Solution", idea.get("solution"))}
        {section("Suggested improvement", idea.get("suggested_improvement"))}
        {section("Potential impact", idea.get("potential_impact"))}
        {section("Target audience", idea.get("target_audience"))}
        {section("Usage scenarios", idea.get("usage_scenarios"))}
        {section("Extra opportunity", idea.get("extra_opportunity"))}
        {section("Extra context", idea.get("extra_context"))}

        <hr style="margin-top:30px;">
        <p style="color:#888; font-size:12px;">
          Generated by InstaIdeas
        </p>
      </body>
    </html>
    """

def response(status, body):
    return {
        "statusCode": status,
        "headers": {
            "Content-Type": "application/json",
            "Access-Control-Allow-Origin": "*"
        },
        "body": json.dumps(body)
    }